import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'tables.dart';

/// Hand-written database class; app_database.g.dart is auto-generated by Drift's build_runner.
part 'app_database.g.dart';

@DriftDatabase(tables: [Auth])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_open());

  @override
  int get schemaVersion => 1;

  static QueryExecutor _open() {
    /// Configures drift_flutter to handle platform-specific paths and run queries on a background isolate.
    return driftDatabase(name: 'backlogforge');
  }
}
