import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'tables.dart';
import 'games_dao.dart';
import 'settings_dao.dart';

/// Hand-written database class; app_database.g.dart is auto-generated by Drift's build_runner.
part 'app_database.g.dart';

const int schemaVersionNumber = 2;

@DriftDatabase(tables: [Games, AppSettings], daos: [GamesDao, SettingsDao])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_open());

  @override
  int get schemaVersion => schemaVersionNumber;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) async {
      await m.createAll();
      await _seedSettings();
    },
    onUpgrade: (m, fromVersion, toVersion) async {
      /// Migration from schema version 1 to 2: Drop auth table (moving to flutter_secure_storage)
      if (fromVersion < schemaVersionNumber) {
        await m.deleteTable('auth');
        await m.createTable(appSettings);
        await _seedSettings();
      }
    },
  );

  Future<void> _seedSettings() => into(
    appSettings,
  ).insertOnConflictUpdate(AppSettingsCompanion.insert(id: const Value(1)));

  static QueryExecutor _open() => driftDatabase(name: 'backlogforge');
}
